

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title><?= $this->title;?></title>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css">
    <!-- Bootstrap core CSS -->
    <link href="css/bootstrap.min.css" rel="stylesheet">
    <!-- Material Design Bootstrap -->
    <link href="css/mdb.min.css" rel="stylesheet">
    <link rel="stylesheet" href="/dht11/main.css" />
</head>
<body>
<header>
   <div class="container"> <img alt="tuturu" src="tuturu.png" /></div>
</header>
<div class="container">
<?= $this->body;?></div>
<footer>

</footer>


<script type="text/javascript" src="js/jquery-3.3.1.min.js"></script>
<!-- Bootstrap tooltips -->
<script type="text/javascript" src="js/popper.min.js"></script>
<!-- Bootstrap core JavaScript -->
<script type="text/javascript" src="js/bootstrap.min.js"></script>
<!-- MDB core JavaScript -->
<script type="text/javascript" src="js/mdb.js"></script>
<script type="text/javascript" src="js/script.js"></script>
</body>
</body>
</html>
