<div>



    <h2>stats test
      <input type="number" id="da" max="30"><button id="go">ici</button>
      <div class="row">
      <div class="col-6">
        <canvas id="lineChart" style="max-width: 500px;"></canvas>
</div>

<div class="col-6">
<p id="titre"></p>
<div id="moy"></div>
<div id="min"></div>
<div id='max'></div>


</div>
</div>


    </h2>
    <h1>Température </h1>
    <?php
    global $error;
    if (!empty($error)){
        echo '<div class="alert alert-danger">'.$error.'</div>';
    }
    else{
    $temp = $this->temp;


    echo "Température : " . $temp->temperature;
    echo " Humidité : " . $temp->humidite;
    echo "<br> La date est : " . date("d M y");


    echo "<br>Dernière modification le " . $temp->date;

    $tempInt = (int)$temp->temperature;
    $height = ($tempInt / 50 * 195) + 160;
    $top = (($tempInt + 30) * 4) * -1 + 435;

    ?>
    <br>
    <img alt="rien" src="thermometer.jpg" id="termo">
    <div class="rouge" style=<?= "\"height:" . $height . "px; top:" . $top . "px;\"</div>";
    }
    ?>
